INSERT INTO "fakultas" ("kode", "nama") VALUES
('STEI',	'Sekolah Teknik Elektro dan Informatika'),
('FTI',	'Fakultas Teknik Industri'),
('FITB',	'Fakultas Ilmu dan Teknologi Kebumian'),
('FMIPA',	'Fakultas Matematika dan Ilmu Pengetahuan Alam'),
('FSRD',	'Fakultas Seni Rupa dan Desain'),
('FTMD',	'Fakultas Teknik Mesin dan Dirgantara'),
('FTTM',	'Fakultas Teknik Pertambangan dan Perminyakan'),
('FTSL',	'Fakultas Teknik Sipil dan Lingkungan'),
('SAPPK',	'Sekolah Arsitektur, Perencanaan dan Pengembangan Kebijakan'),
('SBM',	'Sekolah Bisnis dan Manajemen'),
('SF',	'Sekolah Farmasi'),
('SITH',	'Sekolah Ilmu dan Teknologi Hayati'),
('SPS', 'Sekolah Pascasarjana'),
('NONFS', 'Non Fakultas');