INSERT INTO modul (kode_mata_kuliah, nama, deskripsi) VALUES
('IF3110', 'Modul 1', 'Ini Modul 1 Pengembangan Aplikasi Berbasis Web'),
('IF3110', 'Modul 2', 'Ini Modul 2 Pengembangan Aplikasi Berbasis Web'),
('IF3110', 'Modul 3', 'Ini Modul 3 Pengembangan Aplikasi Berbasis Web'),
('IF3110', 'Modul 4', 'Ini Modul 4 Pengembangan Aplikasi Berbasis Web'),
('IF3110', 'Modul 5', 'Ini Modul 5 Pengembangan Aplikasi Berbasis Web'),
('IF3130', 'Modul 1', 'Ini Modul 1 Jaringan Komputer'),
('IF3130', 'Modul 2', 'Ini Modul 2 Jaringan Komputer'),
('IF3130', 'Modul 3', 'Ini Modul 3 Jaringan Komputer'),
('IF3130', 'Modul 4', 'Ini Modul 4 Jaringan Komputer'),
('IF3130', 'Modul 5', 'Ini Modul 5 Jaringan Komputer'),
('IF3140', 'Modul 1', 'Ini Modul 1 Manajemen Basis Data'),
('IF3140', 'Modul 2', 'Ini Modul 2 Manajemen Basis Data'),
('IF3140', 'Modul 3', 'Ini Modul 3 Manajemen Basis Data'),
('IF3140', 'Modul 4', 'Ini Modul 4 Manajemen Basis Data'),
('IF3140', 'Modul 5', 'Ini Modul 5 Manajemen Basis Data'),
('IF3141', 'Modul 1', 'Ini Modul 1 Sistem Informasi'),
('IF3141', 'Modul 2', 'Ini Modul 2 Sistem Informasi'),
('IF3141', 'Modul 3', 'Ini Modul 3 Sistem Informasi'),
('IF3141', 'Modul 4', 'Ini Modul 4 Sistem Informasi'),
('IF3141', 'Modul 5', 'Ini Modul 5 Sistem Informasi'),
('IF3150', 'Modul 1', 'Ini Modul 1 Manajemen Proyek Perangkat Lunak'),
('IF3150', 'Modul 2', 'Ini Modul 2 Manajemen Proyek Perangkat Lunak'),
('IF3150', 'Modul 3', 'Ini Modul 3 Manajemen Proyek Perangkat Lunak'),
('IF3150', 'Modul 4', 'Ini Modul 4 Manajemen Proyek Perangkat Lunak'),
('IF3150', 'Modul 5', 'Ini Modul 5 Manajemen Proyek Perangkat Lunak'),
('IF3151', 'Modul 1', 'Ini Modul 1 Interaksi Manusia Komputer'),
('IF3151', 'Modul 2', 'Ini Modul 2 Interaksi Manusia Komputer'),
('IF3151', 'Modul 3', 'Ini Modul 3 Interaksi Manusia Komputer'),
('IF3151', 'Modul 4', 'Ini Modul 4 Interaksi Manusia Komputer'),
('IF3151', 'Modul 5', 'Ini Modul 5 Interaksi Manusia Komputer'),
('IF3170', 'Modul 1', 'Ini Modul 1 Inteligensi Buatan'),
('IF3170', 'Modul 2', 'Ini Modul 2 Inteligensi Buatan'),
('IF3170', 'Modul 3', 'Ini Modul 3 Inteligensi Buatan'),
('IF3170', 'Modul 4', 'Ini Modul 4 Inteligensi Buatan'),
('IF3170', 'Modul 5', 'Ini Modul 5 Inteligensi Buatan');