INSERT INTO program_studi (kode, kode_fakultas, nama) VALUES
('101', 'FMIPA', 'Matematika'),
('102', 'FMIPA', 'Fisika'),
('103', 'FMIPA', 'Astronomi'),
('105', 'FMIPA', 'Kimia'),
('108', 'FMIPA', 'Aktuaria'),
('160', 'FMIPA', 'Tahap Tahun Pertama FMIPA'),
('201', 'FMIPA', 'Matematika'),
('202', 'FMIPA', 'Fisika'),
('203', 'FMIPA', 'Astronomi'),
('205', 'FMIPA', 'Kimia'),
('208', 'FMIPA', 'Aktuaria'),
('209', 'FMIPA', 'Sains Komputasi'),
('246', 'FMIPA', 'Pengajaran Matematika'),
('247', 'FMIPA', 'Pengajaran Fisika'),
('248', 'FMIPA', 'Pengajaran Kimia'),
('249', 'FMIPA', 'Ilmu dan Rekayasa Nuklir'),
('301', 'FMIPA', 'Matematika'),
('302', 'FMIPA', 'Fisika'),
('303', 'FMIPA', 'Astronomi'),
('305', 'FMIPA', 'Kimia'),
('349', 'FMIPA', 'Rekayasa Nuklir'),
('104', 'SITH', 'Mikrobiologi'),
('106', 'SITH', 'Biologi'),
('112', 'SITH', 'Rekayasa Hayati'),
('114', 'SITH', 'Rekayasa Pertanian'),
('115', 'SITH', 'Rekayasa Kehutanan'),
('119', 'SITH', 'Teknologi Pasca Panen'),
('161', 'SITH', 'Tahap Tahun Pertama SITH'),
('198', 'SITH', 'Tahap Tahun Pertama SITH'),
('206', 'SITH', 'Biologi'),
('211', 'SITH', 'Bioteknologi'),
('213', 'SITH', 'Biomanajemen'),
('306', 'SITH', 'Biologi'),
('107', 'SF', 'Sains dan Teknologi Farmasi'),
('116', 'SF', 'Farmasi Klinik dan Komunitas'),
('162', 'SF', 'Tahap Tahun Pertama SF'),
('907', 'SF', 'Profesi Apoteker'),
('207', 'SF', 'Farmasi'),
('217', 'SF', 'Keolahragaan'),
('218', 'SF', 'Farmasi Industri'),
('307', 'SF', 'Farmasi'),
('121', 'FTTM', 'Teknik Pertambangan'),
('122', 'FTTM', 'Teknik Perminyakan'),
('123', 'FTTM', 'Teknik Geofisika'),
('125', 'FTTM', 'Teknik Metalurgi'),
('164', 'FTTM', 'Tahap Tahun Pertama FTTM'),
('221', 'FTTM', 'Rekayasa Pertambangan'),
('222', 'FTTM', 'Teknik Perminyakan'),
('223', 'FTTM', 'Teknik Geofisika'),
('225', 'FTTM', 'Teknik Metalurgi'),
('226', 'FTTM', 'Teknik Geotermal'), ('321', 'FTTM', 'Rekayasa Pertambangan'), ('322', 'FTTM', 'Teknik Perminyakan'),
('323', 'FTTM', 'Teknik Geofisika'),
('120', 'FITB', 'Teknik Geologi'),
('128', 'FITB', 'Meteorologi'),
('129', 'FITB', 'Oseanografi'),
('151', 'FITB', 'Teknik Geodesi dan Geomatika'),
('163', 'FITB', 'Tahap Tahun Pertama FITB'),
('220', 'FITB', 'Teknik Geologi'),
('224', 'FITB', 'Sains Kebumian'),
('227', 'FITB', 'Teknik Air Tanah'),
('251', 'FITB', 'Teknik Geodesi dan Geomatika'),
('320', 'FITB', 'Teknik Geologi'),
('324', 'FITB', 'Sains Kebumian'),
('351', 'FITB', 'Teknik Geodesi dan Geomatika'),
('130', 'FTI', 'Teknik Kimia'),
('133', 'FTI', 'Teknik Fisika'),
('134', 'FTI', 'Teknik Industri'),
('143', 'FTI', 'Teknik Pangan'),
('144', 'FTI', 'Manajemen Rekayasa'),
('145', 'FTI', 'Teknik Bioenergi dan Kemurgi'),
('167', 'FTI', 'Tahap Tahun Pertama FTI'),
('230', 'FTI', 'Teknik Kimia'),
('233', 'FTI', 'Teknik Fisika'),
('234', 'FTI', 'Teknik dan Manajemen Industri'),
('238', 'FTI', 'Instrumentasi dan Kontrol'),
('294', 'FTI', 'Logistik'),
('330', 'FTI', 'Teknik Kimia'),
('333', 'FTI', 'Teknik Fisika'),
('334', 'FTI', 'Teknik dan Manajemen Industri'),
('132', 'STEI', 'Teknik Elektro'),
('135', 'STEI', 'Teknik Informatika'),
('165', 'STEI', 'Tahap Tahun Pertama STEI'),
('180', 'STEI', 'Teknik Tenaga Listrik'),
('181', 'STEI', 'Teknik Telekomunikasi'),
('182', 'STEI', 'Sistem dan Teknologi Informasi'),
('183', 'STEI', 'Teknik Biomedis'),
('196', 'STEI', 'Tahap Tahun Pertama STEI'),
('232', 'STEI', 'Teknik Elektro'),
('235', 'STEI', 'Informatika'),
('332', 'STEI', 'Teknik Elektro dan Informatika'),
('131', 'FTMD', 'Teknik Mesin'),
('136', 'FTMD', 'Teknik Dirgantara'),
('137', 'FTMD', 'Teknik Material'),
('169', 'FTMD', 'Tahap Tahun Pertama FTMD'),
('231', 'FTMD', 'Teknik Mesin'),
('236', 'FTMD', 'Teknik Dirgantara'),
('237', 'FTMD', 'Ilmu dan Teknik Material'),
('331', 'FTMD', 'Teknik Mesin'),
('336', 'FTMD', 'Teknik Dirgantara'),
('337', 'FTMD', 'Ilmu dan Teknik Material'),
('150', 'FTSL', 'Teknik Sipil'),
('153', 'FTSL', 'Teknik Lingkungan'),
('155', 'FTSL', 'Teknik Kelautan'),
('157', 'FTSL', 'Rekayasa Infrastruktur Lingkungan'),
('158', 'FTSL', 'Teknik dan Pengelolaan Sumber Daya Air'),
('166', 'FTSL', 'Tahap Tahun Pertama FTSL'),
('250', 'FTSL', 'Teknik Sipil'),
('253', 'FTSL', 'Teknik Lingkungan'),
('255', 'FTSL', 'Teknik Kelautan'),
('257', 'FTSL', 'Pengelolaan Infrastruktur Air Bersih dan Sanitasi'),
('258', 'FTSL', 'Pengelolaan Sumberdaya Air (PSDA)'),
('269', 'FTSL', 'Sistem dan Teknik Jalan Raya'),
('350', 'FTSL', 'Teknik Sipil'),
('353', 'FTSL', 'Teknik Lingkungan'),
('152', 'SAPPK', 'Arsitektur'),
('154', 'SAPPK', 'Perencanaan Wilayah dan Kota'),
('199', 'SAPPK', 'Tahap Tahun Pertama SAPPK'),
('240', 'SAPPK', 'Studi Pembangunan'),
('242', 'SAPPK', 'Transportasi'),
('252', 'SAPPK', 'Arsitektur'),
('254', 'SAPPK', 'Perencanaan Wilayah dan Kota'),
('256', 'SAPPK', 'Rancang Kota'),
('288', 'SAPPK', 'Perencanaan Kepariwisataan'),
('289', 'SAPPK', 'Arsitektur Lanskap'),
('342', 'SAPPK', 'Transportasi'),
('352', 'SAPPK', 'Arsitektur'),
('354', 'SAPPK', 'Perencanaan Wilayah dan Kota'),
('168', 'FSRD', 'Tahap Tahun Pertama FSRD'),
('170', 'FSRD', 'Seni Rupa'),
('172', 'FSRD', 'Kriya'),
('173', 'FSRD', 'Desain Interior'),
('174', 'FSRD', 'Desain Komunikasi Visual'),
('175', 'FSRD', 'Desain Produk'),
('270', 'FSRD', 'Seni Rupa'),
('271', 'FSRD', 'Desain'),
('370', 'FSRD', 'Ilmu Seni Rupa dan Desain'),
('190', 'SBM', 'Manajemen'),
('192', 'SBM', 'Kewirausahaan'),
('197', 'SBM', 'Tahap Tahun Pertama SBM'),
('290', 'SBM', 'Sains Manajemen'),
('291', 'SBM', 'Administrasi Bisnis'),
('293', 'SBM', 'Administrasi Bisnis (Kampus Jakarta)'),
('390', 'SBM', 'Sains Manajemen'),
('287', 'SPS', 'Teknologi Nano'),
('387', 'SPS', 'Sains dan Teknologi Nano'),
('100', 'NONFS', 'Non Reguler S1'),
('179', 'NONFS', 'Mata Kuliah Umum (MKU)'),
('800', 'NONFS', 'IVC'),
('900', 'NONFS', 'Program Profesi Insinyur'),
('914', 'NONFS', 'PPI'),
('915', 'NONFS', 'PPI'),
('920', 'NONFS', 'PPI'),
('921', 'NONFS', 'PPI'),
('922', 'NONFS', 'PPI'),
('923', 'NONFS', 'PPI'),
('925', 'NONFS', 'PPI'),
('930', 'NONFS', 'PPI'),
('931', 'NONFS', 'PPI'),
('932', 'NONFS', 'PPI'),
('933', 'NONFS', 'PPI'),
('934', 'NONFS', 'PPI'),
('935', 'NONFS', 'PPI'),
('936', 'NONFS', 'PPI'),
('937', 'NONFS', 'PPI'),
('950', 'NONFS', 'PPI'),
('951', 'NONFS', 'PPI'),
('953', 'NONFS', 'PPI'),
('954', 'NONFS', 'PPI'),
('955', 'NONFS', 'PPI'),
('200', 'NONFS', 'Non Reguler S2');
